name = "excise-bakaya-api"
main = "worker.js"
compatibility_date = "2024-03-20"

[vars]
FRONTEND_URL = "https://excise-bakaya-form.pages.dev"

# Note: Once you create your D1 database, update the database_id below
[[d1_databases]]
binding = "DB"
database_name = "excise-bakaya-db"
database_id = "667be1f3-7612-45c6-91e9-0a40a451c6ea"
